version: "3.9"
services:
  backend:
    build: ../backend
    container_name: shrinkshield-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
